# Base configuration for SFM Service
# This file contains default settings that are common across all environments

environment: development
debug: false
version: "1.0.0"

# Database configuration
database:
  host: localhost
  port: 5432
  name: sfm_db
  username: sfm_user
  password: ""  # Will be loaded from secrets manager
  pool_size: 10
  timeout: 30
  ssl_mode: disable
  max_connections: 100

# Cache configuration
cache:
  backend: memory
  host: localhost
  port: 6379
  ttl: 3600
  max_size: 1000
  password: ""  # Will be loaded from secrets manager
  db: 0

# API configuration
api:
  host: 0.0.0.0
  port: 8000
  debug: false
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  rate_limit: "100/hour"
  jwt_secret: ""  # Will be loaded from secrets manager
  request_timeout: 30
  max_request_size: 10485760  # 10MB

# Logging configuration
logging:
  level: INFO
  format: json
  file_path: /var/log/sfm/app.log
  file_enabled: false
  console_enabled: true
  rotation_size: 100MB
  rotation_count: 10

# Security configuration
security:
  secret_key: ""  # Will be loaded from secrets manager
  encryption_enabled: false
  encryption_key: ""  # Will be loaded from secrets manager
  audit_enabled: true
  session_timeout: 3600