# Development environment configuration
# Overrides for development environment

environment: development
debug: true

# Database configuration for development
database:
  host: localhost
  port: 5432
  name: sfm_dev_db
  username: sfm_dev_user
  pool_size: 5
  timeout: 10
  ssl_mode: disable

# Cache configuration for development
cache:
  backend: memory
  ttl: 1800  # 30 minutes
  max_size: 500

# Logging configuration for development
logging:
  level: DEBUG
  format: text
  file_enabled: false
  console_enabled: true

# Security configuration for development
security:
  encryption_enabled: false
  audit_enabled: true
  session_timeout: 7200  # 2 hours