# Testing environment configuration
# Overrides for testing environment

environment: testing
debug: false

# Database configuration for testing
database:
  host: localhost
  port: 5432
  name: sfm_test_db
  username: sfm_test_user
  pool_size: 2
  timeout: 5
  ssl_mode: disable
  max_connections: 10

# Cache configuration for testing
cache:
  backend: memory
  ttl: 300  # 5 minutes
  max_size: 100

# Logging configuration for testing
logging:
  level: ERROR
  format: text
  file_enabled: false
  console_enabled: true

# Security configuration for testing
security:
  encryption_enabled: false
  audit_enabled: false
  session_timeout: 600  # 10 minutes