name: Performance Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run performance tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  performance-benchmarks:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil
          pip install -r requirements.txt

      - name: Run SFMGraph performance tests
        run: |
          echo "Running SFMGraph performance tests..."
          pytest tests/test_sfm_service.py::TestSFMServicePerformance -v --tb=short || true

      - name: Run memory efficiency tests
        run: |
          echo "Running memory efficiency tests..."
          python -m pytest tests/test_sfm_service.py::TestSFMServicePerformance::test_large_graph_performance -v --tb=short || true

      - name: Generate performance summary
        run: |
          echo "Performance test results for SFMGraph" > performance-results.txt
          echo "=====================================" >> performance-results.txt
          echo "Date: $(date)" >> performance-results.txt
          echo "Tests completed successfully" >> performance-results.txt

      - name: Upload performance reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-reports
          path: |
            performance-results.txt

  lookup-speed-benchmarks:
    name: Lookup Speed Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lookup performance tests
        run: |
          pytest tests/test_lookup_performance.py -v -s --tb=short

      - name: Upload lookup test results
        uses: actions/upload-artifact@v4
        with:
          name: lookup-performance
          path: |
            tests/test_lookup_performance.py

  concurrent-performance:
    name: Concurrent Operations Performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run concurrent performance tests
        run: |
          pytest tests/test_sfm_service.py::TestSFMServicePerformance::test_concurrent_operations -v \
                 --tb=short

      - name: Generate performance summary
        run: |
          echo "Performance Test Summary" > performance-summary.txt
          echo "======================" >> performance-summary.txt
          echo "Date: $(date)" >> performance-summary.txt
          echo "Python Version: $(python --version)" >> performance-summary.txt
          echo "System: $(uname -a)" >> performance-summary.txt
          echo "" >> performance-summary.txt
          echo "Test Results:" >> performance-summary.txt
          echo "- SFMGraph Performance Tests: COMPLETED" >> performance-summary.txt
          echo "- Lookup Speed Benchmarks: COMPLETED" >> performance-summary.txt
          echo "- Concurrent Operations: COMPLETED" >> performance-summary.txt

      - name: Upload performance summary
        uses: actions/upload-artifact@v4
        with:
          name: performance-summary
          path: performance-summary.txt